#!/bin/bash
#!/bin/bash

find . -type f -iname "*.gif" -print0 | sort -z | while read -d $'\0' file
do
  file=$(echo "$file" | tr '[:upper:]' '[:lower:]')  # convert to lowercase
  filename=$(echo "${file%.*}")  # remove file extension
  echo "$filename"
done

echo  # add a new line at the end

